public enum SfxKey : byte {
    Walk,
    Run,
    Jump,
    Land,
    Reload,
    Dry,
    Shoot,
    JumpPad,
    Grapple,
    BulletTrail,
    HopballSpawn,
    // UI Sounds
    ButtonClick,
    ButtonHover,
    BackButton,
    TimerTick,
    Hit,
    Kill,
    Hurt,
    Tagged,
    Tagging,
    // Weapon-specific shoots
    ShootPistol,
    ShootDeagle,
    ShootSMG,
    ShootRifle,
    ShootShotgun,
    ShootSniper,
    // Weapon-specific reloads
    ReloadPistol,
    ReloadDeagle,
    ReloadSMG,
    ReloadRifle,
    ReloadShotgun,
    ReloadSniper,
    SniperZoom
}